min_log_level: "debug"
server:
  port: 5001
  read_timeout: 10
  write_timeout: 5
  rate_limit:
    rps: 5
    burst: 10
jwt_secret: "jwt_secret"
tracer_host: "http://tracer_host:14268"
grpc:
  auth_service_port: 5010
